// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Http = require("bs-node-http/src/Http.js");
var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Method = require("./Method.bs.js");

function start(request, response, routers) {
  Method.getMethod(Http.ClientRequest.getMethod(request));
  Http.ClientRequest.getUrl(request);
  return List.map((function (router) {
                return Curry._2(router.action, request, response);
              }), routers);
}

exports.start = start;
/* No side effect */
