// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Rest = require("../helpers/Rest.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function jsonResponse(c) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "status",
                c.status
              ],
              /* :: */[
                /* tuple */[
                  "message",
                  c.message
                ],
                /* [] */0
              ]
            ]);
}

var Encode = {
  jsonResponse: jsonResponse
};

function run(request, response) {
  var statusApi = Json.parseOrRaise(" {\n      \"status\": true,\n      \"message\": \"Bem vindo\"\n    } ");
  return Rest.bodyJsonResponse(response, 200, JSON.stringify(statusApi));
}

exports.Encode = Encode;
exports.run = run;
/* No side effect */
