// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Rest = require("../helpers/Rest.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function jsonResponse(c) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "status",
                c.status
              ],
              /* :: */[
                /* tuple */[
                  "dynamics",
                  Json_encode.dict((function (prim) {
                          return prim;
                        }), c.dynamics)
                ],
                /* [] */0
              ]
            ]);
}

var Encode = {
  jsonResponse: jsonResponse
};

function run(param, response) {
  var statusApi = Json.parseOrRaise(" {\n      \"status\": true,\n      \"dynamics\": { \"hello\": \"boa\", \"random\": 8 }\n    } ");
  return Rest.bodyJsonResponse(response, 200, JSON.stringify(statusApi));
}

exports.Encode = Encode;
exports.run = run;
/* No side effect */
