// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Rest = require("../core/Rest.bs.js");

function run(param, response) {
  return Rest.bodyResponse(response, 200, "Sobre nos");
}

exports.run = run;
/* No side effect */
