// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Log = require("./helpers/Log.bs.js");
var ApiHome = require("./api/ApiHome.bs.js");
var Routers = require("./helpers/Routers.bs.js");
var ApiUsers = require("./api/ApiUsers.bs.js");
var PageHome = require("./pages/PageHome.bs.js");
var PageAbout = require("./pages/PageAbout.bs.js");

var routers_000 = {
  method: /* GET */0,
  uri: "/api/users",
  action: ApiUsers.run
};

var routers_001 = /* :: */[
  {
    method: /* GET */0,
    uri: "/api",
    action: ApiHome.run
  },
  /* :: */[
    {
      method: /* GET */0,
      uri: "/",
      action: PageHome.run
    },
    /* :: */[
      {
        method: /* GET */0,
        uri: "/about",
        action: PageAbout.run
      },
      /* [] */0
    ]
  ]
];

var routers = /* :: */[
  routers_000,
  routers_001
];

function start(request, response) {
  return Routers.start(request, response, routers);
}

Log.renderRouters(routers);

exports.routers = routers;
exports.start = start;
/*  Not a pure module */
