// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Http = require("bs-node-http/src/Http.js");
var Rest = require("./helpers/Rest.bs.js");
var ApiHome = require("./api/ApiHome.bs.js");
var ApiUsers = require("./api/ApiUsers.bs.js");
var PageHome = require("./pages/PageHome.bs.js");
var PageAbout = require("./pages/PageAbout.bs.js");

function start(request, response) {
  var methodHttp = Http.ClientRequest.getMethod(request);
  var uri = Http.ClientRequest.getUrl(request);
  if (methodHttp !== 3546230) {
    return Rest.bodyResponse(response, 404, "File not Found");
  }
  switch (uri) {
    case "/" :
        return PageHome.run(request, response);
    case "/about" :
        return PageAbout.run(request, response);
    case "/api" :
        return ApiHome.run(request, response);
    case "/api/users" :
        return ApiUsers.run(request, response);
    default:
      return Rest.bodyResponse(response, 404, "File not Found");
  }
}

console.log("server running in localhost:3000");

exports.start = start;
/*  Not a pure module */
