// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Log = require("./helpers/Log.bs.js");
var Http = require("http");
var Routers = require("./core/Routers.bs.js");

function start(routers, port) {
  var app = Http.createServer((function (request, response) {
          return Routers.start(request, response, routers);
        }));
  Log.renderRouters(routers);
  app.listen(port);
  console.log("server running in localhost:" + port.toString());
  
}

exports.start = start;
/* http Not a pure module */
