// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");
var Server = require("./Server.bs.js");
var Routers = require("./Routers.bs.js");

function start(routers, port) {
  Http.createServer((function (request, response) {
          return Routers.start(request, response, routers);
        }));
  Server.renderRouters(routers);
  console.log("server running in localhost:" + String(port));
  
}

exports.start = start;
/* http Not a pure module */
