// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.bs.js");
var Http = require("http");

var server = Http.createServer(App.start);

server.listen(3000);

console.log("server running in localhost:3000");

exports.server = server;
/* server Not a pure module */
